### ISSUE TITLE
_ChipDeviceCtrl.so is linked against libcrypto.so.1.1

### ISSUE THREAD

**Issue by mweinelt** [home-assistant-libs/chip-wheels#24]
The issue is that OpenSSL 1.1 went end-of-life back in 2023-09 and the Matter integration of Home Assistant still depends on it.

This is likely due to the upstream build system being tied to Ubuntu 20.04, for which I've filed an [issue](https://github.com/project-chip/connectedhomeip/issues/25688) some time ago, but have not received any meaningful feedback yet.

Wondering if this is on your radar and if you have ideas/plans to mitigate this.

**Comment by agners** [comment]
Looking at https://github.com/project-chip/connectedhomeip/blob/v1.2.0.1/src/crypto/BUILD.gn it doesn't look like the build system is requesting any particular OpenSSL version :thinking: 

It seems that Google/Apple uses boringssl mostly, so that probably make bumping OpenSSL not really a priority :cold_sweat: 

It seems that the build system partially got updated to Ubuntu 22.04, and it [seems the intention was to also update the chip-build](https://github.com/project-chip/connectedhomeip/pull/23444/files#r1012308811) container, but it seems it did not receive any love yet :cry:
